### ISSUE TITLE
How to run multiple repeats  of per samples

### ISSUE THREAD

**Issue by q1134269149** [DepledgeLab/DRUMMER#1]
Hi, 
I have three biological duplications of each sample(Control or Exp), I'd like to ask how I should type in the command. Thanks!
hqin

**Comment by DepledgeLab** [comment]
Hello. 
At present, DRUMMER only supports 1-vs-1 comparisons so you would need to run the command three times (one for each pair of control + treatment) and then filter the outputs yourself to find overlapping candidates.

We hope to add functionality in the future that allows multiple inputs in the manner you suggest but this will take to implement and test.

Cheers

Dan

**Comment by q1134269149** [comment]
Hi,
OK. Thank you for your reply.
Cheers

**Comment by q1134269149** [comment]
> Hello.
> At present, DRUMMER only supports 1-vs-1 comparisons so you would need to run the command three times (one for each pair of control + treatment) and then filter the outputs yourself to find overlapping candidates.
> 
> We hope to add functionality in the future that allows multiple inputs in the manner you suggest but this will take to implement and test.
> 
> Cheers
> 
> Dan

I noted that the **Optional flags** contain **adjusted p_value**. How is this value calculated without replications.
Thanks

**Comment by DepledgeLab** [comment]
The adjusted p_value is a Bonferroni-correction of the p_value which is calculated simply by multiplying the p_value by the number of tests performed within a given transcript (e.g. p_value x 1000 if the given transcript is 1000 nt long).

**Comment by q1134269149** [comment]
> The adjusted p_value is a Bonferroni-correction of the p_value which is calculated simply by multiplying the p_value by the number of tests performed within a given transcript (e.g. p_value x 1000 if the given transcript is 1000 nt long).

Thanks. Besides, there is another point that I do not understand.  In README file,  **_DRUMMER can calculate the genomic position of all modifications if provided with a six-column file derived from a BED12 file. This can be easily generated by aligning the transcriptome multi-fasta file against the relevant genome fasta file, parsing to BED12 format, and then extracting relevant columns e.g._**, in this sentence, the **transcriptome multi-fasta file** used to generated .bed file refer to our sequencing data or transcriptome annotation files.
Thanks

**Comment by DepledgeLab** [comment]
When running DRUMMER in 'isoform' mode, sequence reads aligning to each individual transcript are parsed to predict the location of RNA modifications. The position of this modification is reported within the context of the given transcript. However, when specifying a list of transcript names to be analyzed (-u flag) as a single column text file (one transcript per line), we also present the option of instead using a six column text file which is generated according to the instructions. This six-column file provides details on the genomic context of each transcript and allows DRUMMER to annotate the resulting analysis with the genomic position of a modification as well as the transcript position.

The transcriptome multi-fasta file should be a FASTA format file containing all the annotated transcripts associated with your genome of interest. 

An example of this can be found in the TESTDATA folder - Ad5_v9.1_complete.fasta

**Comment by q1134269149** [comment]
> When running DRUMMER in 'isoform' mode, sequence reads aligning to each individual transcript are parsed to predict the location of RNA modifications. The position of this modification is reported within the context of the given transcript. However, when specifying a list of transcript names to be analyzed (-u flag) as a single column text file (one transcript per line), we also present the option of instead using a six column text file which is generated according to the instructions. This six-column file provides details on the genomic context of each transcript and allows DRUMMER to annotate the resulting analysis with the genomic position of a modification as well as the transcript position.
> 
> The transcriptome multi-fasta file should be a FASTA format file containing all the annotated transcripts associated with your genome of interest.
> 
> An example of this can be found in the TESTDATA folder - Ad5_v9.1_complete.fasta

OK! I get it. Thanks.
