### ISSUE TITLE
Reference file when performing against human reference

### ISSUE THREAD

**Issue by AnunayS** [DepledgeLab/DRUMMER#10]
After reading the instructions, I understood that for performing analysis in isoform mode i.e. against transcripts sequence, I need to give transcript file in "-r" options in the DRUMMER command.

Following are two sets of commands which I ran:
1) python3 DRUMMER.py -r ambey/GRCh38.p13.genome.fasta -l ambey/transcripts.txt -o ambey-test -c ambey/48C_1.bam -t ambey/48T_1.bam -a isoform

2) python3 DRUMMER.py -r ambey/GRCh38.p13.genome.fasta -l ambey/transcripts.txt -o ambey-test -c ambey/48C_1.bam -t ambey/48T_1.bam -a isoform

As you can see in 1st command I have given whole genome as reference and in 2nd command I have given transcript sequences, but for some reasons DRUMMER is running in 1st command.

When the 2nd command is run, following error pops-up:
**Traceback (most recent call last):
  File "DRUMMER.py", line 73, in <module>
    test_isoform.main(transcriptome_file,treatment_bam,path_transcripts,control_bam,odds,padj,m6A,fraction_diff,visualization_input,output_dir,'isoform',deletion)
  File "/home/sequencing/DRUMMER/modules/test_isoform.py", line 180, in main
    iterate,length_dictionary,shape_lst = isoform_mode(transcriptome_file,transcript_directory,path_transcripts)
  File "/home/sequencing/DRUMMER/modules/test_isoform.py", line 44, in isoform_mode
    id_file = open(out_file, "w")
FileNotFoundError: [Errno 2] No such file or directory: 'ambey-test/transcripts/ENST00000621191.1|ENSG00000235300.4|OTTHUMG00000132087.3|-|THRA1/BTR-204|THRA1/BTR|513|lncRNA|.fa'**

It might be an issue because in the command written in the manual page:
**python3 /path/to/DRUMMER.py -r TESTDATA/Hsapiens.sample.fasta -l TESTDATA/Hsapiens.sample.transcripts.txt -o isoform-test-human -c TESTDATA/isoform.Hsapiens.MOD.sorted.bam -t TESTDATA/isoform.Hsapiens.UNMOD.sorted.bam -a isoform**

the reference used above is transcripts sequences and not the genomic sequence. 

Please let me know what wrong am I doing.

Thankyou.

**Comment by JonAbebe** [comment]
Hello,

Looking at the error code it seems like the issue stems from the fasta headers.
Programmatically, when Python encounters "/" it assumes this means directory.

So the case of  
ambey-test/transcripts/ENST00000621191.1|ENSG00000235300.4|OTTHUMG00000132087.3|-|THRA1/BTR-204|THRA1/BTR|513|lncRNA|.fa
DRUMMER is looking for a file named 'BTR|513|lncRNA|.fa' in a directory called 'BTR-204|THRA1'.

I believe simply replacing the "/" characters should resolve this issue.

**Comment by AnunayS** [comment]
I am sorry to say but there are no "/" in the text file given.

The text file for the transcripts is generated as suggested in the home page.

**Comment by DepledgeLab** [comment]
One of the first steps DRUMMER performs is to parse the transcriptome fasta file into individual fasta files. These individual fasta files are placed in the  'transcripts' directory  (e.g. ambey-test/transcripts/). Can you let me know what the files in that directory look like? I suspect there is a parsing issue, potentially resulting from the very long fasta headers and/or the presence of pipes (|)

Alternatively, looking more closely at the second command - it looks like you are still using the genome fasta as the reference rather than the transcriptome fasta.

**Comment by AnunayS** [comment]
When using the genome as a reference, all the chromosomes are individually parsed and created in a subfolder under main folder transcripts.

But the same is not happening when done using transcripts as a reference genome.

**Comment by DepledgeLab** [comment]
Can you let me know what the first few lines of the transcripts.txt file look like and also the first few transcript headers in the reference fasta file (e.g. _grep \> reference.fasta | head_).

I cannot reproduce the error you are getting as all our transcripts.txt files work perfectly with our transcriptome reference fasta files.

**Comment by AnunayS** [comment]
the transcripts .ext file is attached here : x-special/nautilus-clipboard
copy
file:///media/sequencing/Linux_Ext_1/Anunay/Hg38_ref_seq/transcripts.txt

transcripts reference is as follows (downloaded from gencode) :
>ENST00000456328.2|ENSG00000223972.5|OTTHUMG00000000961.2|OTTHUMT00000362751.1|DDX11L1-202|DDX11L1|1657|processed_transcript|
GTTAACTTGCCGTCAGCCTTTTCTTTGACCTCTTCTTTCTGTTCATGTGTATTTGCTGTC
TCTTAGCCCAGACTTCCCGTGTCCTTTCCACCGGGCCTTTGAGAGGTCACAGGGTCTTGA
TGCTGTGGTCTTCATCTGCAGGTGTCTGACTTCCAGCAACTGCTGGCCTGTGCCAGGGTG
CAAGCTGAGCACTGGAGTGGAGTTTTCCTGTGGAGAGGAGCCATGCCTAGAGTGGGATGG
GCCATTGTTCATCTTCTGGCCCCTGTTGTCTGCATGTAACTTAATACCACAACCAGGCAT
AGGGGAAAGATTGGAGGAAAGATGAGTGAGAGCATCAACTTCTCTCACAACCTAGGCCAG
TGTGTGGTGATGCCAGGCATGCCCTTCCCCAGCATCAGGTCTCCAGAGCTGCAGAAGACG
ACGGCCGACTTGGATCACACTCTTGTGAGTGTCCCCAGTGTTGCAGAGGCAGGGCCATCA
GGCACCAAAGGGATTCTGCCAGCATAGTGCTCCTGGACCAGTGATACACCCGGCACCCTG
TCCTGGACACGCTGTTGGCCTGGATCTGAGCCCTGGTGGAGGTCAAAGCCACCTTTGGTT
CTGCCATTGCTGCTGTGTGGAAGTTCACTCCTGCCTTTTCCTTTCCCTAGAGCCTCCACC
ACCCCGAGATCACATTTCTCACTGCCTTTTGTCTGCCCAGTTTCACCAGAAGTAGGCCTC
TTCCTGACAGGCAGCTGCACCACTGCCTGGCGCTGTGCCCTTCCTTTGCTCTGCCCGCTG
GAGACGGTGTTTGTCATGGGCCTGGTCTGCAGGGATCCTGCTACAAAGGTGAAACCCAGG
AGAGTGTGGAGTCCAGAGTGTTGCCAGGACCCAGGCACAGGCATTAGTGCCCGTTGGAGA
AAACAGGGGAATCCCGAAGAAATGGTGGGTCCTGGCCATCCGTGAGATCTTCCCAGGGCA
GCTCCCCTCTGTGGAATCCAATCTGTCTTCCATCCTGCGTGGCCGAGGGCCAGGCTTCTC
ACTGGGCCTCTGCAGGAGGCTGCCATTTGTCCTGCCCACCTTCTTAGAAGCGAGACGGAG
CAGACCCATCTGCTACTGCCCTTTCTATAATAACTAAAGTTAGCTGCCCTGGACTATTCA
CCCCCTAGTCTCAATTTAAGAAGATCCCCATGGCCACAGGGCCCCTGCCTGGGGGCTTGT
CACCTCCCCCACCTTCTTCCTGAGTCATTCCTGCAGCCTTGCTCCCTAACCTGCCCCACA
GCCTTGCCTGGATTTCTATCTCCCTGGCTTGGTGCCAGTTCCTCCAAGTCGATGGCACCT
CCCTCCCTCTCAACCACTTGAGCAAACTCCAAGACATCTTCTACCCCAACACCAGCAATT
GTGCCAAGGGCCATTAGGCTCTCAGCATGACTATTTTTAGAGACCCCGTGTCTGTCACTG
AAACCTTTTTTGTGGGAGACTATTCCTCCCATCTGCAACAGCTGCCCCTGCTGACTGCCC
TTCTCTCCTCCCTCTCATCCCAGAGAAACAGGTCAGCTGGGAGCTTCTGCCCCCACTGCC
TAGGGACCAACAGGGGCAGGAGGCAGTCACTGACCCCGAGACGTTTGCATCCTGCACAGC
TAGAGATCCTTTATTAAAAGCACACTGTTGGTTTCTG
>ENST00000450305.2|ENSG00000223972.5|OTTHUMG00000000961.2|OTTHUMT00000002844.2|DDX11L1-201|DDX11L1|632|transcribed_unprocessed_pseudogene|
GTGTCTGACTTCCAGCAACTGCTGGCCTGTGCCAGGGTGCAAGCTGAGTTGGAGGAAAGA
TGAGTGAGAGCATCAACTTCTCTCACAACCTAGGCCAGTGTGTGGTGATGCCAGGCATGC
CCTTCCCCAGCATCAGGTCTCCAGAGCTGCAGAAGACGACGGCCGACTTGGATCACACTC
TTCTCAGAGCCCAGGCCAGGGGCCCCCAAGAAAGGCTCTGGTGGAGAACCTGTGCATGAA
GGCTGTCAACCAGTCCATAGGCAGGGCCATCAGGCACCAAAGGGATTCTGCCAGCATAGT
GCTCCTGGACCAGTGATACACCCGGCACCCTGTCCTGGACACGCTGTTGGCCTGGATCTG
AGCCCTGGTGGAGGTCAAAGCCACCTTTGGTTCTGCCATTGCTGCTGTGTGGAATTTCAC
CAGAAGTAGGCCTCTTCCTGACAGGCAGCTGCACCACTGCCTGGCGCTGTGCCCTTCCTT
TGCTCTGCCCGCTGGAGACGGTGTTTGTCATGGGCCTGGTCTGCAGGGATCCTGCTACAA
AGGTGAAACCCAGGAGAGTGTGGAGTCCAGAGTGTTGCCAGGACCCAGGCACAGGCATTA
GTGCCCGTTGGAGAAAACAGGGGAATCCCGAA
>ENST00000488147.1|ENSG00000227232.5|OTTHUMG00000000958.1|OTTHUMT00000002839.1|WASH7P-201|WASH7P|1351|unprocessed_pseudogene|

**Comment by AnunayS** [comment]
the transcript file looks like this :

chr1	ENST00000456328.2|ENSG00000223972.5|OTTHUMG00000000961.2|OTTHUMT00000362751.1|DDX11L1-202|DDX11L1|1657|processed_transcript|	+	11868	3	359,109,1189	0,744,1352
chr1	ENST00000450305.2|ENSG00000223972.5|OTTHUMG00000000961.2|OTTHUMT00000002844.2|DDX11L1-201|DDX11L1|632|transcribed_unprocessed_pseudogene|	+	12009	6	55,43,85,83,150,218	0,175,603,965,1215,1443
chr1	ENST00000488147.1|ENSG00000227232.5|OTTHUMG00000000958.1|OTTHUMT00000002839.1|WASH7P-201|WASH7P|1351|unprocessed_pseudogene|	-	14403	11	100,31,152,159,198,136,137,147,99,154,37	0,604,1392,2203,2454,2829,3202,3511,3864,10334,15130
chr1	ENST00000633703.1|ENSG00000282458.1|OTTHUMG00000180466.8|OTTHUMT00000471181.1|WASH5P-207|WASH5P|571|processed_transcript|	-	22212	3	393,154,24	0,2525,7108
chr1	ENST00000632089.1|ENSG00000282458.1|OTTHUMG00000180466.8|OTTHUMT00000471183.4|WASH5P-203|WASH5P|398|processed_transcript|	-	24213	3	226,154,18	0,524,5107
chr1	ENST00000631994.1|ENSG00000282458.1|OTTHUMG00000180466.8|OTTHUMT00000475090.1|WASH5P-202|WASH5P|548|processed_transcript|	-	24769	2	122,426	0,4764
chr1	ENST00000633603.1|ENSG00000282807.3|OTTHUMG00000180451.3|OTTHUMT00000451407.2|AC008993.3-001|AC008993.3|631|lncRNA|	+	30170	2	497,134	0,805
chr1	ENST00000408365.1|ENSG00000283921.1|-|-|MIR1302-9-201|MIR1302-9|138|miRNA|	+	30365	1	138	0
chr1	ENST00000417324.1|ENSG00000237613.2|OTTHUMG00000000960.1|OTTHUMT00000002842.1|FAM138A-201|FAM138A|1187|lncRNA|	-	34553	3	621,205,361	0,723,1167
chr1	ENST00000631376.1|ENSG00000282591.1|OTTHUMG00000180467.4|OTTHUMT00000451424.4|FAM138F-201|FAM138F|1183|lncRNA|	-	34553	3	621,205,357	0,723,1167
chr1	ENST00000632948.1|ENSG00000282591.1|OTTHUMG00000180467.4|OTTHUMT00000451425.3|FAM138F-202|FAM138F|1201|lncRNA|	-	34610	2	871,330	0,1110
chr1	ENST00000461467.1|ENSG00000237613.2|OTTHUMG00000000960.1|OTTHUMT00000002843.1|FAM138A-202|FAM138A|590|lncRNA|	-	35244	2	237,353	0,476
chr1	ENST00000606857.1|ENSG00000268020.3|OTTHUMG00000185779.1|OTTHUMT00000471235.1|OR4G4P-201|OR4G4P|840|unprocessed_pseudogene|	+	52472	1	840	0
chr1	ENST00000642116.1|ENSG00000240361.2|OTTHUMG00000001095.3|OTTHUMT00000492680.1|OR4G11P-202|OR4G11P|1414|processed_transcript|	+	57597	3	56,157,1201	0,1102,5318



the reference transcript  file is downloaded from gencode and looks as follows 

>ENST00000456328.2|ENSG00000223972.5|OTTHUMG00000000961.2|OTTHUMT00000362751.1|DDX11L1-202|DDX11L1|1657|processed_transcript|
GTTAACTTGCCGTCAGCCTTTTCTTTGACCTCTTCTTTCTGTTCATGTGTATTTGCTGTC
TCTTAGCCCAGACTTCCCGTGTCCTTTCCACCGGGCCTTTGAGAGGTCACAGGGTCTTGA
TGCTGTGGTCTTCATCTGCAGGTGTCTGACTTCCAGCAACTGCTGGCCTGTGCCAGGGTG
CAAGCTGAGCACTGGAGTGGAGTTTTCCTGTGGAGAGGAGCCATGCCTAGAGTGGGATGG
GCCATTGTTCATCTTCTGGCCCCTGTTGTCTGCATGTAACTTAATACCACAACCAGGCAT
AGGGGAAAGATTGGAGGAAAGATGAGTGAGAGCATCAACTTCTCTCACAACCTAGGCCAG
TGTGTGGTGATGCCAGGCATGCCCTTCCCCAGCATCAGGTCTCCAGAGCTGCAGAAGACG
ACGGCCGACTTGGATCACACTCTTGTGAGTGTCCCCAGTGTTGCAGAGGCAGGGCCATCA
GGCACCAAAGGGATTCTGCCAGCATAGTGCTCCTGGACCAGTGATACACCCGGCACCCTG
TCCTGGACACGCTGTTGGCCTGGATCTGAGCCCTGGTGGAGGTCAAAGCCACCTTTGGTT
CTGCCATTGCTGCTGTGTGGAAGTTCACTCCTGCCTTTTCCTTTCCCTAGAGCCTCCACC
ACCCCGAGATCACATTTCTCACTGCCTTTTGTCTGCCCAGTTTCACCAGAAGTAGGCCTC
TTCCTGACAGGCAGCTGCACCACTGCCTGGCGCTGTGCCCTTCCTTTGCTCTGCCCGCTG
GAGACGGTGTTTGTCATGGGCCTGGTCTGCAGGGATCCTGCTACAAAGGTGAAACCCAGG
AGAGTGTGGAGTCCAGAGTGTTGCCAGGACCCAGGCACAGGCATTAGTGCCCGTTGGAGA
AAACAGGGGAATCCCGAAGAAATGGTGGGTCCTGGCCATCCGTGAGATCTTCCCAGGGCA
GCTCCCCTCTGTGGAATCCAATCTGTCTTCCATCCTGCGTGGCCGAGGGCCAGGCTTCTC
ACTGGGCCTCTGCAGGAGGCTGCCATTTGTCCTGCCCACCTTCTTAGAAGCGAGACGGAG
CAGACCCATCTGCTACTGCCCTTTCTATAATAACTAAAGTTAGCTGCCCTGGACTATTCA
CCCCCTAGTCTCAATTTAAGAAGATCCCCATGGCCACAGGGCCCCTGCCTGGGGGCTTGT
CACCTCCCCCACCTTCTTCCTGAGTCATTCCTGCAGCCTTGCTCCCTAACCTGCCCCACA
GCCTTGCCTGGATTTCTATCTCCCTGGCTTGGTGCCAGTTCCTCCAAGTCGATGGCACCT
CCCTCCCTCTCAACCACTTGAGCAAACTCCAAGACATCTTCTACCCCAACACCAGCAATT
GTGCCAAGGGCCATTAGGCTCTCAGCATGACTATTTTTAGAGACCCCGTGTCTGTCACTG
AAACCTTTTTTGTGGGAGACTATTCCTCCCATCTGCAACAGCTGCCCCTGCTGACTGCCC
TTCTCTCCTCCCTCTCATCCCAGAGAAACAGGTCAGCTGGGAGCTTCTGCCCCCACTGCC
TAGGGACCAACAGGGGCAGGAGGCAGTCACTGACCCCGAGACGTTTGCATCCTGCACAGC
TAGAGATCCTTTATTAAAAGCACACTGTTGGTTTCTG
>ENST00000450305.2|ENSG00000223972.5|OTTHUMG00000000961.2|OTTHUMT00000002844.2|DDX11L1-201|DDX11L1|632|transcribed_unprocessed_pseudogene|
GTGTCTGACTTCCAGCAACTGCTGGCCTGTGCCAGGGTGCAAGCTGAGTTGGAGGAAAGA
TGAGTGAGAGCATCAACTTCTCTCACAACCTAGGCCAGTGTGTGGTGATGCCAGGCATGC
CCTTCCCCAGCATCAGGTCTCCAGAGCTGCAGAAGACGACGGCCGACTTGGATCACACTC
TTCTCAGAGCCCAGGCCAGGGGCCCCCAAGAAAGGCTCTGGTGGAGAACCTGTGCATGAA
GGCTGTCAACCAGTCCATAGGCAGGGCCATCAGGCACCAAAGGGATTCTGCCAGCATAGT
GCTCCTGGACCAGTGATACACCCGGCACCCTGTCCTGGACACGCTGTTGGCCTGGATCTG
AGCCCTGGTGGAGGTCAAAGCCACCTTTGGTTCTGCCATTGCTGCTGTGTGGAATTTCAC
CAGAAGTAGGCCTCTTCCTGACAGGCAGCTGCACCACTGCCTGGCGCTGTGCCCTTCCTT
TGCTCTGCCCGCTGGAGACGGTGTTTGTCATGGGCCTGGTCTGCAGGGATCCTGCTACAA
AGGTGAAACCCAGGAGAGTGTGGAGTCCAGAGTGTTGCCAGGACCCAGGCACAGGCATTA
GTGCCCGTTGGAGAAAACAGGGGAATCCCGAA
>ENST00000488147.1|ENSG00000227232.5|OTTHUMG00000000958.1|OTTHUMT00000002839.1|WASH7P-201|WASH7P|1351|unprocessed_pseudogene|

**Comment by DepledgeLab** [comment]
For the reference transcript file, I do not see any > symbols at the start of each header line - are these really missing or is this just a formatting issue? Note that they should be present as they are required to parse the multi-fasta file.

If that doesn't work then I would still be concerned about the presence of pipes "|" in the input files. You could try and remove these (and a lot of the text) to simplify the reference fasta file as follows: sed 's/|.*$//g' input > output 

Then you would simplify the transcript.txt file: sed 's/|*|//g' transcripts.txt > transcripts.simplified.txt

If this works correctly then you would retain just the transcript ID in the header (e.g. ENST00000488147.1) rather than the full header (e.g. ENST00000488147.1|ENSG00000227232.5|OTTHUMG00000000958.1|OTTHUMT00000002839.1|WASH7P-201|WASH7P|1351|unprocessed_pseudogene|)

**Comment by AnunayS** [comment]
Thanks a lot.
The above suggestion worked fine.

But after a while, the following error pops up:
RUNNING in isoform

**[('48C_1_aligned_-48T_1_aligned_', ('ambey/48C_1_aligned_reads.bam', 'ambey/48T_1_aligned_reads.bam'))]
Traceback (most recent call last):
  File "DRUMMER.py", line 73, in <module>
    test_isoform.main(transcriptome_file,treatment_bam,path_transcripts,control_bam,odds,padj,m6A,fraction_diff,visualization_input,output_dir,'isoform',deletion)
  File "/home/sequencing/DRUMMER/modules/test_isoform.py", line 194, in main
    summary_df = run_summary(output_dir+'/'+repl + '/complete_analysis/',m6A_status)
  File "/home/sequencing/DRUMMER/modules/summary.py", line 15, in run_summary
    onlydir = ['/'+f for f in listdir(target_dir) if isfile(join(target_dir, f))]
FileNotFoundError: [Errno 2] No such file or directory: 'ambey/isoform-test-human1/48C_1_aligned_-48T_1_aligned_/complete_analysis/'**

I am running DRUMMER in its home directory only by copying all the input files there itself.

**Comment by JonAbebe** [comment]
Usually this error occurs when one of the intermediate step fails, I suspect an issue with mapping..
Could you check the files within ambey/isoform-test-human1/48C_1_aligned_-48T_1_aligned_/bam_readcount to see if there is data within these files?

**Comment by AnunayS** [comment]
Yes the folder has files with names as
chr1.MOD.bamreadcount.txt
chr1.UNMOD.bamreadcount.txt

But all are 0 bytes in size

**Comment by DepledgeLab** [comment]
I think the issue here is that the mapping identities in the SAM file will contain the full header (e.g. ENST00000488147.1|ENSG00000227232.5|OTTHUMG00000000958.1|OTTHUMT00000002839.1|WASH7P-201|WASH7P|1351|unprocessed_pseudogene|) whereas the bamreadcount step is looking for the simple header (e.g. ENST00000488147.1). Unfortunately the only way around this is to re do the transcriptome alignment step with the simplified FASTA reference file (i.e. where the transcript headers are shortened to the transcript ID only (e.g. >ENST00000488147.1).

We will look to address this issue in future iterations of DRUMMER but for now that workaround should be appropriate.

**Comment by AnunayS** [comment]
Hi.
Thanks for the prompt responses.

I did changes what you suggested.

I first corrected the raw transcript fasta file by using sed command (gencode.v38.transcripts.header.corrected.fasta). I used it to map my raw files using minimap2 splice function.

Then i extracted transcripts list by (mentioned in home page)
- mapping transcript (original gencode file, not header corrected) against genome sequence.
- creating bam, sorting and making bed file.
- extracting transcript file in txt format from bed file.
- cutting 2 column from the transcript and using sed command again to clean the file (2.txt)
[2.txt](https://github.com/DepledgeLab/DRUMMER/files/7208136/2.txt)

Ultimately the reference and list files have same headings as explained before. But still the error comes (image file)
![Screenshot from 2021-09-22 11-32-03](https://user-images.githubusercontent.com/85170013/134292676-7cf1c184-7488-486f-b772-bb939523749d.png)

**Comment by JonAbebe** [comment]
This is a good start. Getting this error does not necessarily mean DRUMMER did not work. 
Usually this occurs for cases where a transcript exists in one dataset and not the other. 
For example, ENST0000044230.1 may exist in the UNMOD dataset but not in the MOD dataset. This would cause one of the bam-readcount files to be empty and thus the merging of the two datasets would fail to merge.

One thing you can do to avoid this error is to extract a list of transcripts that occur in each dataset, and find the intersection of the two (find the transcripts that both UNMOD and MOD have in common), and use this as the transcript file. I showed an example of this at the bottom of the github main page, "Alternative Setting up a transcript list file (Larger transcriptomes)". 

But I suspect if you let DRUMMER run to completion, despite these warnings, it would get you results.
