### ISSUE TITLE
Problems running drummer.py

### ISSUE THREAD

**Issue by acarmas1** [DepledgeLab/DRUMMER#13]
I have been trying to run drummer.py to identigy the m6A modifications in my direct RNA sequecing reads of honey bees. However, when I run this code: 

module load python3
module load anaconda3/2021.05
module load samtools/1.10
module load bedtools/2.27.1

python /projects/dsn001/camila/programs/DRUMMER/DRUMMER.py -r GCF_003254395.2_Amel_HAv3.1_genomic.fna \
-n NC_037638.1 -c alnWT_drum_sorted.bam \
-t alnKO_drum_sorted.bam -o exome_DRUMMER -a exome -m true

I'm getting this error:

RUNNING in exome

Current Comparison: alnKO_drum_sorted.bam vs alnWT_drum_sorted.bam
Traceback (most recent call last):
  File "/projects/dsn001/camila/programs/DRUMMER/DRUMMER.py", line 55, in <module>
    test_exome.main(transcriptome_file,treatment_bam,name,control_bam,odds,padj,m6A,fraction_diff,output_dir,'exome',deletion)
  File "/projects/dsn001/camila/programs/DRUMMER/modules/test_exome.py", line 194, in main
    summary_df = run_summary(output_dir+'/'+repl + '/complete_analysis/',m6A_status)
  File "/projects/dsn001/camila/programs/DRUMMER/modules/summary.py", line 41, in run_summary
    final_candidates = all_candidates[keep_columns]
  File "/opt/anaconda3/2021.05/lib/python3.8/site-packages/pandas/core/frame.py", line 3030, in __getitem__
    indexer = self.loc._get_listlike_indexer(key, axis=1, raise_missing=True)[1]
  File "/opt/anaconda3/2021.05/lib/python3.8/site-packages/pandas/core/indexing.py", line 1266, in _get_listlike_indexer
    self._validate_read_indexer(keyarr, indexer, axis, raise_missing=raise_missing)
  File "/opt/anaconda3/2021.05/lib/python3.8/site-packages/pandas/core/indexing.py", line 1308, in _validate_read_indexer
    raise KeyError(f"None of [{key}] are in the [{axis_name}]")
KeyError: "None of [Index(['chr_ctrl', 'ref_ctrl', 'pos_ctrl', 'depth_ctrl', 'depth_treat',\n       'ref_fraction_ctrl', 'ref_fraction_treat', 'frac_diff', $

Please, could someone help me to solve it.

**Comment by DepledgeLab** [comment]
Hello, 

At present, drummer.py needs to be run from within the directory itself. i.e.

cd /projects/dsn001/camila/programs/DRUMMER/

python DRUMMER.py -r GCF_003254395.2_Amel_HAv3.1_genomic.fna -n NC_037638.1 -c alnWT_drum_sorted.bam -t alnKO_drum_sorted.bam -o exome_DRUMMER -a exome -m true

We are working on a general fix for this and hope to have something soon. We will also update the troubleshooting section to make this more clear.

**Comment by acarmas1** [comment]
I appreciate your help, it worked. 

Thank you
