### ISSUE TITLE
about coverage cutoff

### ISSUE THREAD

**Issue by xieyy46** [DepledgeLab/DRUMMER#17]
Hi developer! I want to know how you set coverage cutoff ? I can not find this information in your code. Thank you!

**Comment by JonAbebe** [comment]
Hello,
There is no maximum cutoff for DRUMMER. DRUMMER calls bam-readcount to parse the alignments, so as long as bam-readcount is working properly,  the data from alignment should be reflected in DRUMMER.

On the other hand for a minimum cutoff, we simply get rid of any location with no alignment. Here is the line in the mergy.py script (line 93):
filtered_df = filtered_df[filtered_df['depth'] != 0].reset_index(drop=True)
If you want to adjust this value you can change the logic here, more than happy to help.
