### ISSUE TITLE
Run Errors

### ISSUE THREAD

**Issue by q1134269149** [DepledgeLab/DRUMMER#2]
Hi,
   When I ran the isoform mode, I get an EXIT with: 
"**_nohup: ignoring input 
Mus_musculus.GRCm38.p6_rna.fasta
/home/qinh/softs/DRUMMER/drummer.sh: line 80: conditional binary operator expected
Mus_musculus.GRCm38.p6_rna.fasta
/home/qinh/softs/DRUMMER/drummer.sh: line 80: conditional binary operator expected_**
"
What caused it? 
Thanks
hqin

**Comment by q1134269149** [comment]
The parameter of "-u" was the **transcripts.txt** that generated with your suggestion:
"**DRUMMER can calculate the genomic position of all modifications if provided with a six-column file derived from a BED12 file. This can be easily generated by aligning the transcriptome multi-fasta file against the relevant genome fasta file, parsing to BED12 format, and then extracting relevant columns** ". Head of this file was:
_**"XR_003949180.1  +       3102015 1       110     0
XM_006495550.4  -       3199732 2       7585,3532       0,13706
NM_001011874.1  -       3214481 1       2489    0
XM_011238395.3  -       3670548 1       1400    0
XM_011238412.1  -       4115672 14      276,45,59,155,152,133,87,200,108,178,213,177,92,233     0,3995,4342,26939,32139,32939,48182,54532,81861,90987,110938,112770,115380,127460
XM_017313202.1  -       4115672 14      276,45,59,155,152,133,87,200,108,178,213,177,92,545     0,3995,4342,26939,32139,32939,48182,54532,81861,90987,110938,112770,115380,117511
XM_017313203.1  -       4115672 15      276,45,59,155,152,133,87,200,108,178,213,177,92,104,293 0,3995,4342,26939,32139,32939,48182,54532,81861,90987,110938,112770,115380,117511,117763
XM_030252325.1  -       4119737 23      336,155,152,133,87,200,108,178,213,177,92,130,32,77,76,79,152,133,87,164,172,636,97     0,22874,28074,28874,44117,50467,77796,86922,106873,108705,111315,123395,123679,123805,125293,141789,147731,165028,173188,191532,232172,232464,289432
NM_001370921.1  -       4119865 23      208,155,152,133,87,200,108,178,213,177,92,130,32,77,76,79,152,133,87,164,172,636,104    0,22746,27946,28746,43989,50339,77668,86794,106745,108577,111187,123267,123551,123677,125165,141661,147603,164900,173060,191404,232044,232336,240334
NM_001195662.1  -       4290845 4       2167,172,636,72 0,61064,61356,118324**_
"
I'm not sure if this is the problem.

**Comment by q1134269149** [comment]
When I ran your TESTDATA data also gave the same ERROR.

**Comment by DepledgeLab** [comment]
Thanks for raising this issue. 

The error you are getting "/home/qinh/softs/DRUMMER/drummer.sh: line 80: conditional binary operator expected" is due to using an older version of BASH (i.e. < v4.2). You can check your bash version using 'bash --version' 

Details on how to upgrade bash (I'm guessing you are using OSX) can be found here - https://itnext.io/upgrading-bash-on-macos-7138bd1066ba

**Comment by q1134269149** [comment]
> As a temporary fix, I have made a new version of the executable file called drummer_oldbash.sh
> 
> This has been tested on bash v3.7 and found to function correctly so you can try this as an alternative to updating your bash installation

thank you!
