### ISSUE TITLE
fastq data

### ISSUE THREAD

**Issue by rania-o** [DepledgeLab/DRUMMER#20]
Hello,
I'm using Drummer to analyze my data, and I wanted to test it on yours as well (all data, not just the available subset).
I was wondering if it's possible to have the fastq data used in your article? I only found the fast5 files which are very big.
Thank you,
Rania

**Comment by DepledgeLab** [comment]
Hello,

We are not able to upload the full fastq dataset to GitHub as it is too large but we can share it with you by other means. Can you send an email to jonathan.abebe[at]nyulangone.org and specify which datasets you want (including guppy version).

**Comment by rania-o** [comment]
Hi @DepledgeLab 
Thank you for your quick response. I just sent an email.
Rania
