### ISSUE TITLE
What does "N" means in the output 

### ISSUE THREAD

**Issue by rania-o** [DepledgeLab/DRUMMER#23]
Hi developers,

I have a question about the output. I want to know what does "N" represent in the output of complete analysis ? I thought it was the indels, but each time the number doesn't match the one displayed in IGV.
Could you please tell me what do you count exactly for the column "N" ?

Rania

**Comment by DepledgeLab** [comment]
Hello. 

"N" represents the total number of observed insertion/deletion events. This is different from a calculation of depth as deletions are treated differently. Consider the following situation in which a single position is covered by 14 reads.

A = 5
+A = 7
-A = 2

The depth would be calculated 10 (5+7-2) whereas the observed events ("N") would be 14 (5+7+2).

Note also that we derive all identified indels at a position from the bamreadcounts output. I am not sure if IGV internally filters low abundance indels when higher abundance indels are present at the same position.
