### ISSUE TITLE
How I get the transcriptome reference for Ad5?

### ISSUE THREAD

**Issue by thadasps** [DepledgeLab/DRUMMER#24]
Hi, I want to use this tools for transcriptome analysis but I confues about step alignment. In general I can get the reference genome to study in genome level for Ad5 from NCBI but I don't know how to get transcriptome reference for Transcriptome-level alignment. Are we use the coding sequence from NCBI as the transcriptome reference? If not, Can you suggest me how to solve this.

Thank you

**Comment by DepledgeLab** [comment]
Hello. You can find the Ad5 transcriptome fasta in the TESTDATA folder (Ad5_v9.1_complete.fasta). This comprises all known Ad5 RNAs present in the v9 annotation. 

Note however there is now a v10 annotation (https://github.com/DepledgeLab/Ad5-annotation) that was recently published (https://pubmed.ncbi.nlm.nih.gov/36095031/). I can provide a transcriptome fasta for this if needed.

**Comment by thadasps** [comment]
Thank you very much.

**Comment by kwonej0617** [comment]
I am wondering if you have a gtf file for Ad5_v.9.1 or a transcriptome reference for V10. Thank you!

**Comment by DepledgeLab** [comment]
Hello. We have GFF3 files for the Ad5 v10.1 transcriptome reference. These can be found here at https://github.com/DepledgeLab/Ad5-annotation. 

For converting from GFF3 to GTF, you could use gffread (https://github.com/gpertea/gffread) or AGAT (https://agat.readthedocs.io/en/latest/gff_to_gtf.html)

**Comment by kwonej0617** [comment]
Thank you so much!
