### ISSUE TITLE
Error when it is complete. 

### ISSUE THREAD

**Issue by DayeaPark** [DepledgeLab/DRUMMER#26]
HI, 
I am currently running DRUMMER and have this error. I cannot understand why it happens. Do you know how I can fix it? I am running for m6A detection using isoform mode. Here is the error message below. 

Thanks! 

.
.
completed..ENSMUST00000222435.1|ENSMUSG00000062382.9|OTTMUSG00000067661.1|OTTMUST00000163758.1|Ftl1-ps1-202|Ftl1-ps1|938|UTR5:1-195|CDS:196-747|UTR3:748-938|
completed..ENSMUST00000239442.1|ENSMUSG00000055320.18|OTTMUSG00000036056.10|-|Tead1-217|Tead1|9962|UTR5:1-506|CDS:507-1817|UTR3:1818-9962|
completed..ENSMUST00000239483.1|ENSMUSG00000027520.16|OTTMUSG00000002659.4|OTTMUST00000182403.1|Zdbf2-204|Zdbf2|12523|UTR5:1-395|CDS:396-7892|UTR3:7893-12523|
all.aligned.transcrip-l3.aligned.transcrip - total sites - 1921
Traceback (most recent call last):
  File "/scratch/users/dyp/Analysis/Nanopore/DRUMMER/DRUMMER/DRUMMER.py", line 74, in <module>
    test_isoform.main(transcriptome_file,treatment_bam,path_transcripts,control_bam,odds,padj,m6A,fraction_diff,visualization_input,output_dir,'isoform',deletion)
  File "/scratch/users/dyp/Analysis/Nanopore/DRUMMER/DRUMMER/modules/test_isoform.py", line 205, in main
    top_3 = return_top3_transcripts(output_dir+'/'+repl + '/complete_analysis/')
  File "/scratch/users/dyp/Analysis/Nanopore/DRUMMER/DRUMMER/modules/test_isoform.py", line 168, in return_top3_transcripts
    max_mean = max(current_df['mean'])
ValueError: max() arg is an empty sequence

**Comment by JonAbebe** [comment]
Hello,

This error does not affect DRUMMER results as this is just a little functionality we included to quickly see transcripts with the highest depth. This error is simply stating that DRUMMER cannot return any transcripts for some reason. For now, could you comment out lines 205 and 206 in the test_isoform.py file? This should bypass this step and allow DRUMMER to finish. 

Also, consider changing the headers for your transcripts. Sometimes, complex transcript can lead to the tool throwing out errors or issues with output paths. We have a better explanation in the troubleshooting section of the tool's main page.

Try these two things and let me know how it goes.

Thanks, 

Jonathan
