### ISSUE TITLE
scope of the application of DRUMMER

### ISSUE THREAD

**Issue by fulaibaowang** [DepledgeLab/DRUMMER#27]
Hi,

i am wondering how good is xpore detect other RNA modification like ψ and ADP-ribosylation or is it mainly designed for m6A/RNA methylation?

Thanks in advance!

Yun

**Comment by DepledgeLab** [comment]
I'm going to assume you mean DRUMMER and not xPore (as this is the DRUMMER repository...).

We haven't tested DRUMMER extensively with other modifications (aside from m6A) but as long as a modification produces a change in current that manifests in an increased error rate at (or proximal to) a modified position then DRUMMER should be able to detect it.
