### ISSUE TITLE
Issues about output

### ISSUE THREAD

**Issue by q1134269149** [DepledgeLab/DRUMMER#3]
Hi, 
I ran DRUMMER with my nanopore data, I only got three very large folders:
**_bam_readcount ( 11501568 bp), map(30773248 bp), transcripts(16384 bp)_**.
And the log file also very large(788375223 bp). I ran this program for two weeks before it ended.
I do not get the single output file which you described in README. I don't know what the problem is. The command are as follows:

_**for i in *.fasta
do
minimap2 -t 32 -ax splice -uf -k14 --secondary=no $ref/Mus_musculus.GRCm38.p6_rna.fna $i > ${i}.sam
samtools view -F 2304 -b -o ${i}.bam ${i}.sam
samtools sort -@ 32 -o ${i}.sort.bam ${i}.bam
samtools index ${i}.sort.bam
done

drummer.sh -r Mus_musculus.GRCm38.p6_rna.fasta -u $ref/Mus_musculus.transcriptome.sort.txt -c mESCs.Mettl14.WT.SRR11550261.fasta.sort.bam -t mESCs.Mettl14.KO.SRR11550260.fasta.sort.bam -o DRUMMER_mESCs.Mettl14 -m isoform**_

Thank you!

**Comment by DepledgeLab** [comment]
When successful, DRUMMER should be generating 9 output folders (within the output directory) and should also create a single output file for each transcript being analyzed. The fact you only have 3 output folders suggests that something has failed along the way. 

Could you try the following.

1: Repeat the DRUMMER step you have shown above but include only the first 50 transcripts in your $ref/Mus_musculus.transcriptome.sort.txt file

2: Extract the last 100 lines of the log file to a new text file and upload here so we can have a look through and help troubleshoot.
