### ISSUE TITLE
analyse the output result of drummer.sh 

### ISSUE THREAD

**Issue by aman21392** [DepledgeLab/DRUMMER#5]
[ENST00000370321.8.complete.txt](https://github.com/DepledgeLab/DRUMMER/files/5422440/ENST00000370321.8.complete.txt)
[ENST00000396651.8.complete.txt](https://github.com/DepledgeLab/DRUMMER/files/5422441/ENST00000396651.8.complete.txt)
 I just upload 2 files can you go through please and tell me how to i identify the m6A modified bases. It give less reads because we done experiment as such way so it always give less reads like in our result shown. So on this basis how i know the modified bases, I just want to know this method. 
Thanks in advance

**Comment by JonAbebe** [comment]
Apologies for the delay. 
After completion, the column candidate_site should have the label "candidate" at sites DRUMMER determines is modified.

I had a look at the DRUMMER output you provided, it seems that your average depth is around 25. 
Currently, we are determining the minimum depth DRUMMER needs to make candidate calls. Unfortunately, it looks like a depth of 25 would be too low to make any calls.

**Comment by aman21392** [comment]
yeah i understand it, there are less read depth in my file but i told you i done  experiment in such a way in which the depth of reads are always less in number. This experiment is very sensitive so we always get less number of fastq reads. There is any way we can say it is modified.
Thanks in advance for your valuable suggestions.

**Comment by JonAbebe** [comment]
Have you attempted to use Samtools merge on multiple runs to increase the depth?

**Comment by aman21392** [comment]
No because I just run the sample only 1 time so i just have 2 reads file (wild_type and knockdown condition) not multiple read files. So if i want increase the depth we must have run the sample in duplicate or triplicate. There is no way to got the conclusion from these results.
Thanks in advance for your valuable suggestions

**Comment by DepledgeLab** [comment]
Can I ask what samples you are running? There may well be a subset of genes/transcripts that will have suitable read depths for analysis with DRUMMER. Generally housekeeping genes are good for this.
