### ISSUE TITLE
Requirement of reads' depth

### ISSUE THREAD

**Issue by q1134269149** [DepledgeLab/DRUMMER#6]
Hi,
I ran DRUMMER, however, I don't seem to find an option to set reads depth. And I want to know what the default depth of reads is? And because of particularity of materials, the average depth of my data is only about 20, is it suitable to run the DRUMMER?
Thanks
hqin

**Comment by q1134269149** [comment]
In addition, After ran DRUMMER with **100 transcptional ID list**, I got **100 files**, such as "AT1G01350.1.complete.txt", and **eight folders** : bam_readcount, filtered, gTest, map, merged, motif_information, odds_ratio and transcripts. When I check the "AT1G01350.1.complete.txt" file, I found that the last column (**candidate_site**) has no value. 
The command was: "$soft/drummer.sh -r $transRef -u test.txt -c VIR13_rep1_cdna_filter.bam -t vir14_rep1_cdna_filter.bam -o DRUMMER.out/output_files/rep1 -m isoform". 
And the log file was:
[Uploading run_DRUMMER_rep1.log…]()

I don't know if this output is normal? And how do I handle so many individual txt files?
Thanks
hqin

**Comment by DepledgeLab** [comment]
Apologies for the delay in getting back to you.

We are still working out the minimum range of read depths at which DRUMMER can reliably identify modifications but I strongly suspect a read depth of 20 is far too low. Most likely you will need a minumum of 50-200.

We are currently working toward an updated release of DRUMMER which vastly simplifies the output. This should be released by the end of this week (v0.2) so please try that out. See also the updated readme which better described the new outputs.
