### ISSUE TITLE
ModuleNotFoundError: No module named 'modules.gtest' 

### ISSUE THREAD

**Issue by al3xMlt** [DepledgeLab/DRUMMER#7]
Hello

after running the set-up:

git clone https://github.com/DepledgeLab/DRUMMER

conda env create --file environment-setup.yml 

conda activate DRUMMER

python DRUMMER.py -h 
shows following error: 

Traceback (most recent call last):
  File "DRUMMER.py", line 2, in <module>
    import modules.test_isoform as test_isoform
  File "~/DRUMMER/modules/test_isoform.py", line 7, in <module>
    from modules.gtest import run_gtest
ModuleNotFoundError: No module named 'modules.gtest'

Thanks in advance!
Alex

**Comment by JonAbebe** [comment]
Apologies. I deleted the wrong version of the gtest module while updating github.
I just corrected the issue.

Everything should work now.

Thanks.

**Comment by al3xMlt** [comment]
Thanks for your fast reply!! Now this error shows up:

Traceback (most recent call last):
  File "DRUMMER.py", line 2, in <module>
    import modules.test_isoform as test_isoform
  File "~/DRUMMER/modules/test_isoform.py", line 14, in <module>
    from modules.m6a_summary import run_plotting
  File "~DRUMMER/modules/m6a_summary.py", line 16, in <module>
    from statsmodels.stats import weightstats as stests
ModuleNotFoundError: No module named 'statsmodels'

**Comment by JonAbebe** [comment]
Did you re-download the environment-setup.yml file?
You may be using an older verison.

**Comment by al3xMlt** [comment]
Was my bad! 
Thanks a lot for the fast help!

**Comment by JonAbebe** [comment]
Happy to help.
