### ISSUE TITLE
Error occurred during drummer pipeline

### ISSUE THREAD

**Issue by aman21392** [DepledgeLab/DRUMMER#8]
Hi, I run your test data and my own data and it give same error. The below command i used for your test dataset:----
python /home/aclab/apps/DRUMMER/DRUMMER.py -r /home/aclab/apps/DRUMMER/TESTDATA/Ad5_v9.1_complete.fasta -l /home/aclab/apps/DRUMMER/TESTDATA/Ad5.sample.transcripts.txt -o /Drive4/m6A_modification/Drummer_un_m6A_vs_m6A/ -c /home/aclab/apps/DRUMMER/TESTDATA/isoform.Ad5.MOD.bam -t /home/aclab/apps/DRUMMER/TESTDATA/isoform.Ad5.UNMOD.bam -a isoform -m True

Here's the full error which I got:------
SAMTOOLS in path
Bedtools in path
isoform

     ________________________________
    | __   __                 __  __ |
    ||  \ |_/ |  | |\/| |\/| |_  |_/ |
    ||__/ | \ |__| |  | |  | |__ | \ |
    |________________________________|

RUNNING in isoform

[('isoform.Ad5.MOD-isoform.Ad5.UNMOD', ('/home/aclab/apps/DRUMMER/TESTDATA/isoform.Ad5.MOD.bam', '/home/aclab/apps/DRUMMER/TESTDATA/isoform.Ad5.UNMOD.bam'))]
Traceback (most recent call last):
  File "/home/aclab/apps/DRUMMER/DRUMMER.py", line 73, in <module>
    test_isoform.main(transcriptome_file,treatment_bam,path_transcripts,control_bam,odds,padj,m6A,fraction_diff,visualization_input,output_dir,'isoform',deletion)
  File "/home/aclab/apps/DRUMMER/modules/test_isoform.py", line 194, in main
    summary_df = run_summary(output_dir+'/'+repl + '/complete_analysis/',m6A_status)
  File "/home/aclab/apps/DRUMMER/modules/summary.py", line 15, in run_summary
    onlydir = ['/'+f for f in listdir(target_dir) if isfile(join(target_dir, f))]
FileNotFoundError: [Errno 2] No such file or directory: '/Drive4/m6A_modification/Drummer_un_m6A_vs_m6A//isoform.Ad5.MOD-isoform.Ad5.UNMOD/complete_analysis/'

I run both exome and isoform mode and both give errors.
Please can you sort out this issue? I installed the latest version from GitHub but there is no change.
Thanks in advance

**Comment by aman21392** [comment]
Thanks for your reply, now it works fine. When I run the command then it seems another error:--

[('compiled_m6A-compiled_unmodifi', ('/Drive4/m6A_modification/modified/drummer/compiled_m6A.sort.bam', '/Drive4/m6A_modification/unmodified/drummer/compiled_unmodified.sort.bam'))]
Problem merging: gene8
Problem merging: gene5

/Drive4/NL43_m6A_modification/Drummer_un_m6A_vs_m6A//compiled_m6A-compiled_unmodifi/bam_readcount/gene8.MOD.bamreadcount.txt /Drive4/NL43_m6A_modification/Drummer_un_m6A_vs_m6A//compiled_m6A-compiled_unmodifi/bam_readcount/gene8.UNMOD.bamreadcount.txt
/Drive4/NL43_m6A_modification/Drummer_un_m6A_vs_m6A//compiled_m6A-compiled_unmodifi/bam_readcount/gene5.MOD.bamreadcount.txt /Drive4/NL43_m6A_modification/Drummer_un_m6A_vs_m6A//compiled_m6A-compiled_unmodifi/bam_readcount/gene5.UNMOD.bamreadcount.txt

Can you just tell me what this error means? Thanks

**Comment by JonAbebe** [comment]
Usually this error occurs when one or more bamreadcount file is empty. 
Can you check the contents of these files to make sure they have data?
gene8.MOD.bamreadcount.txt
gene8.UNMOD.bamreadcount.txt
gene5.MOD.bamreadcount.txt
gene5.UNMOD.bamreadcount.txt
