### ISSUE TITLE
alignment against human genome

### ISSUE THREAD

**Issue by AnunayS** [DepledgeLab/DRUMMER#9]
I am trying to use drummer to identify modifications in human RNA samples.

I will have to use -exome option while using, but what option should be used in "-n name of genome (exome)" because human genome GRCh38.p13.genome fasta availble at Gencode has fasta sequence with headers for all the 23 chromosomes.

I tried with >Chr1 but it failed.

Please let me know what changes can I do if I need to map against the human genome sequence.

Thank you.

**Comment by JonAbebe** [comment]
I would hesitate using exome mode on Eukaryotic genomes as this would take a long time, given the large genome and relatively small coding region. Exome mode is targeted for small poorly annotated genomes, i.e. some viral genomes.

However, if you want, try removing the '>' and running it. Also note that the minimap2 alignment step is slightly different for this as well. You would have to align using '-ax splice' as opposed to '-ax map-ont'

But I would advise using -isoform mode and referring to the genomic-position column to identify where in the genome these modifications may be occurring.

**Comment by DepledgeLab** [comment]
I would echo the comment about not using exome mode for large gene sparse genomes. Exome mode is only suitable for small gene dense genomes (e.g. viruses, some bacteria, etc). 

If you are working with a poorly defined large gene sparse genome then it is better to spend time building a basic transcriptome annotation (this can be done using the same sequencing data you generated for the RNA mod analysis) and then running an isoform level analysis.
